import React from 'react';
import { Card, Button, Typography, Space, Tag, Toast, Banner } from '@douyinfe/semi-ui';
import { IconCode, IconCopy } from '@douyinfe/semi-icons';
import { useDeploymentStore } from '../store/deploymentStore';
import { useI18n } from '../hooks/useI18n';

const { Title, Text } = Typography;

export const TemplatePage: React.FC = () => {
  const { currentConfig, generatedYaml } = useDeploymentStore();
  const { t } = useI18n();

  const handleCopy = () => {
    navigator.clipboard.writeText(generatedYaml);
    Toast.success(t('templateCopied'));
  };

  return (
    <div className="page-wrapper">
      <div className="page-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
        <div>
          <Title heading={2} className="page-title">{t('currentTemplate')}</Title>
          <Text className="page-subtitle">{t('currentTemplateSubtitle')}</Text>
        </div>
        <Button theme="solid" type="primary" icon={<IconCopy />} onClick={handleCopy}>{t('copyYaml')}</Button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 300px', gap: '24px' }}>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <Banner type="warning" closeIcon={null} title={t('validationTitle')}>
            {t('validationNote')}
          </Banner>
          <Card className="devops-card" bodyStyle={{ padding: 0, overflow: 'hidden' }}>
            <div className="preview-header" style={{ padding: '12px 16px', borderBottom: '1px solid var(--semi-color-border)', backgroundColor: 'rgba(255,255,255,0.02)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Space>
                <IconCode style={{ color: 'var(--semi-color-text-2)' }} />
                <Text strong>{t('yamlPreview')}</Text>
              </Space>
              <Tag size="small" color="blue">{t('autoGenerated')}</Tag>
            </div>
            <div className="yaml-preview" style={{ padding: '24px', backgroundColor: '#000', overflowX: 'auto' }}>
              <pre style={{ margin: 0, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace', fontSize: '13px', lineHeight: 1.6, color: '#e5e5e5' }}>
                {generatedYaml}
              </pre>
            </div>
          </Card>
        </div>

        <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
          <Card className="devops-card" title={<span style={{ fontWeight: 600 }}>{t('templateMetadata')}</span>}>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <Text type="tertiary" size="small">{t('projectName')}</Text>
                <Text strong>{currentConfig.projectName}</Text>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <Text type="tertiary" size="small">{t('deploymentMode')}</Text>
                <Tag color="cyan" style={{ alignSelf: 'flex-start' }}>{currentConfig.deployMode}</Tag>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <Text type="tertiary" size="small">{t('repository')}</Text>
                <Text link>{currentConfig.repository.owner}/{currentConfig.repository.repo}</Text>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                <Text type="tertiary" size="small">{t('servicesIncluded')}</Text>
                <Space wrap>
                  <Tag size="small" type="ghost">{t('serviceApi')}</Tag>
                  {currentConfig.deployMode !== 'cluster-slave' && currentConfig.services.useInternalPostgres && <Tag size="small" type="ghost">{t('servicePostgres')}</Tag>}
                  {currentConfig.deployMode !== 'cluster-slave' && currentConfig.services.useInternalRedis && <Tag size="small" type="ghost">{t('serviceRedis')}</Tag>}
                </Space>
              </div>
            </div>
          </Card>
          
          <Card className="devops-card" title={<span style={{ fontWeight: 600 }}>{t('usageInstructions')}</span>}>
             <Text type="tertiary" style={{ display: 'block', marginBottom: 12 }}>
                {t('currentTemplateSubtitle')}
              </Text>
              <Text type="tertiary" style={{ display: 'block', marginBottom: 12 }}>
                 {t('templateInstruction')}
               </Text>
              <div style={{ padding: '12px', backgroundColor: '#000', borderRadius: 6, border: '1px solid var(--semi-color-border)' }}>
                 <Text code style={{ color: '#e5e5e5', backgroundColor: 'transparent' }}>{t('templateCliHint')}</Text>
              </div>
           </Card>
        </div>
      </div>
    </div>
  );
};
