import { stringify } from 'yaml'
import type { DeploymentConfig } from '../types/deployment'

function buildSqlDsn(config: DeploymentConfig) {
  if (config.deployMode === 'cluster-slave' || !config.services.useInternalPostgres) {
    return config.services.externalSqlDsn || '${SQL_DSN}'
  }

  return 'postgresql://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}'
}

function buildRedisConnString(config: DeploymentConfig) {
  if (config.deployMode === 'cluster-slave' || !config.services.useInternalRedis) {
    return config.services.externalRedisConnString || '${REDIS_CONN_STRING}'
  }

  return '${REDIS_URI}'
}

export function generateZeaburYaml(config: DeploymentConfig): string {
  const includeSharedInfra = config.deployMode !== 'cluster-slave'
  const appNodeType = config.deployMode === 'cluster-slave' ? 'slave' : config.cluster.nodeType
  const parsedRepoId = Number(config.repository.repoId)
  const hasRepoId = Number.isFinite(parsedRepoId) && parsedRepoId > 0

  const templateObject = {
    apiVersion: 'zeabur.com/v1',
    kind: 'Template',
    metadata: {
      name: config.projectName || 'MirrorZeabur Project',
    },
    spec: {
      description: `Generated by MirrorZeabur for ${config.repository.owner || 'owner'}/${config.repository.repo || 'repo'}`,
      tags: ['AI', 'Gateway', 'Tool'],
      services: [
        ...(includeSharedInfra
          ? [
              {
                name: 'PostgreSQL',
                template: 'PREBUILT',
                spec: {
                  source: { image: 'postgres:15' },
                  ports: [{ id: 'database', port: 5432, type: 'TCP' }],
                  env: {
                    POSTGRES_DB: { default: 'new-api', expose: true },
                    POSTGRES_USERNAME: { default: 'postgres', expose: true },
                    POSTGRES_PASSWORD: { default: '${PASSWORD}', expose: true },
                    POSTGRES_HOST: { default: '${CONTAINER_HOSTNAME}', expose: true },
                  },
                },
              },
            ]
          : []),
        ...(includeSharedInfra
          ? [
              {
                name: 'Redis',
                template: 'PREBUILT',
                spec: {
                  source: { image: 'redis:7' },
                  ports: [{ id: 'database', port: 6379, type: 'TCP' }],
                  env: {
                    REDIS_URI: { default: 'redis://${CONTAINER_HOSTNAME}:6379', expose: true },
                  },
                },
              },
            ]
          : []),
        {
          name: 'New API',
          template: 'GIT',
          ...(includeSharedInfra ? { dependencies: ['PostgreSQL', 'Redis'] } : {}),
          spec: {
            source: {
              source: 'GITHUB',
              repo: hasRepoId ? parsedRepoId : 0,
              branch: config.repository.branch || 'main',
            },
            ports: [{ id: 'http', port: 3000, type: 'HTTP' }],
            env: {
              SQL_DSN: { default: buildSqlDsn(config) },
              REDIS_CONN_STRING: { default: buildRedisConnString(config) },
              SESSION_SECRET: { default: config.secrets.sessionSecret || '${PASSWORD}' },
              CRYPTO_SECRET: { default: config.secrets.cryptoSecret || '${PASSWORD}' },
              TZ: { default: config.runtime.tz },
              ERROR_LOG_ENABLED: { default: String(config.runtime.errorLogEnabled) },
              BATCH_UPDATE_ENABLED: { default: String(config.cluster.batchUpdateEnabled) },
              BATCH_UPDATE_INTERVAL: { default: String(config.cluster.batchUpdateInterval) },
              SYNC_FREQUENCY: { default: String(config.cluster.syncFrequency) },
              NODE_TYPE: { default: appNodeType },
              FRONTEND_BASE_URL: { default: config.runtime.frontendBaseUrl || '' },
              LOG_SQL_DSN: { default: config.runtime.logSqlDsn || '' },
            },
          },
        },
      ],
    },
  }

  return `# yaml-language-server: $schema=https://schema.zeabur.app/template.json\n${stringify(templateObject)}`
}
